# Arynox OS - Main Boot Entry
title   Arynox OS
efi     /EFI/arynox/linux.efi
initrd  /EFI/arynox/initramfs.img
options root=UUID=ROOT_UUID rootflags=subvol=@ rw quiet splash rd.systemd.show_status=auto loglevel=3 mitigations=auto
