# Arynox OS - Snapshot Boot Entry (template)
title   Arynox OS (Snapshot: @SNAPSHOT_NAME@)
efi     /EFI/arynox/linux.efi
initrd  /EFI/arynox/initramfs.img
options root=UUID=ROOT_UUID rootflags=subvol=@snapshots/@SNAPSHOT_ID@/snapshot rw quiet splash
